export const ORDERS_ACTION_TYPES = {
  FETCH_ORDERS_START: 'FETCH_ORDERS_START',
  FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
  FETCH_ORDERS_FAILED: 'FETCH_ORDERS_FAILED',
  
  FETCH_ORDER_DETAILS_START: 'FETCH_ORDER_DETAILS_START',
  FETCH_ORDER_DETAILS_SUCCESS: 'FETCH_ORDER_DETAILS_SUCCESS',
  FETCH_ORDER_DETAILS_FAILED: 'FETCH_ORDER_DETAILS_FAILED',
  
  CREATE_ORDER_START: 'CREATE_ORDER_START',
  CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
  CREATE_ORDER_FAILED: 'CREATE_ORDER_FAILED',
  
  UPDATE_ORDER_STATUS_START: 'UPDATE_ORDER_STATUS_START',
  UPDATE_ORDER_STATUS_SUCCESS: 'UPDATE_ORDER_STATUS_SUCCESS',
  UPDATE_ORDER_STATUS_FAILED: 'UPDATE_ORDER_STATUS_FAILED',
  
  SET_SELECTED_ORDER: 'SET_SELECTED_ORDER',
  RESET_ORDER_STATE: 'RESET_ORDER_STATE',
};
